Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Propertise:
      GroupDescription: SSH access via port
      SecurityGroupIngress:
        - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0